HRIS-223 [FE] Integrate remove schedule functionality
framgia/sph-hris pull request #187
Opened 2023-04-27 06:21 UTC by JohnRoyCabezas

## Issue Link

[Backlog Link](https://framgiaph.backlog.com/board/HRIS?selectedIssueKey=HRIS-223)

## Definition of Done

- [x] Users can delete a schedule
- [x] Users cannot delete a schedule that has employees under it

## Pre-condition

run docker

## Expected Output

Users can delete a schedule
Users cannot delete a schedule that has employees under it

## Screenshots/Recordings

Proof:
[screen-capture.webm](https://user-images.githubusercontent.com/109579325/234776492-665120eb-8e66-4ddb-8339-a724fb5e511a.webm)

2023-04-27 09:19 UTC, jsvelte commented on client/src/components/templates/ScheduleManagementLayout/index.tsx
> +          void queryClient.invalidateQueries()
Please specify the query you need to invalidate.

2023-04-27 09:37 UTC, jsvelte commented on client/src/components/templates/ScheduleManagementLayout/index.tsx
> +          void queryClient.invalidateQueries()
```suggestion
          void queryClient.invalidateQueries(['GET_ALL_EMPLOYEE_SCHEDULE']).then(() => {
              onClose()
              toast.success('Deleted Successfully!')
          })
```

2023-04-27 09:38 UTC, jsvelte commented on client/src/components/templates/ScheduleManagementLayout/index.tsx
> +        onSettled: () => {
Please remove onSettled function for the submitting behavior

2023-04-27 09:38 UTC, jsvelte requested changes
Please let me know if this will work

2023-04-27 10:15 UTC, jsvelte approved these changes
# Approved 💯

2023-04-27 10:16 UTC, JohnRoyCabezas commented on client/src/components/templates/ScheduleManagementLayout/index.tsx
> +          void queryClient.invalidateQueries()
Sir, I added the onClose() function outside the mutation as the modal will not close if ever, we receive an error from the backend.

2023-04-28 02:17 UTC, abduljalilpalala approved these changes
### Approved! ✅

2023-04-28 02:18 UTC, merged