HRIS-22 [FE] Integrate timesheet table functionality
framgia/sph-hris pull request #19
Opened 2023-01-13 04:27 UTC by arden-dave

## Issue Link
https://framgiaph.backlog.com/view/HRIS-22

## Definition of Done
- [x] Able to fetch and display the data from the backend

## Notes
- Currently static user (id is 1)

## Pre-condition

Commands to run
- `docker compose up --build`
- go to `http://localhost:3000/my-daily-time-record`

## Expected Output
- All timesheet of a single employee should be displayed

## Screenshots/Recordings
![image](https://user-images.githubusercontent.com/111718037/212237197-5cd9635d-b245-4684-929f-34cbdf96685e.png)

2023-01-17 10:06 UTC, jsvelte commented on client/src/components/molecules/DTRManagementTable/index.tsx
> +        {/* <pre>{JSON.stringify(table, null, 2)}</pre> */}
Please removed this comment

2023-01-17 10:08 UTC, jsvelte commented on client/src/pages/my-daily-time-record.tsx
> +  // const { data, error, isLoading } = getEmployeeTimesheet(user.data?.userById.id as number)
Please remove this comments

2023-01-17 10:09 UTC, jsvelte approved these changes
# Approved 💯

2023-01-18 02:00 UTC, rogeliojohnoliverio approved these changes
Approved 🙇

2023-01-18 02:22 UTC, abduljalilpalala commented on client/src/components/molecules/DTRManagementTable/index.tsx
> +    data: ITimeEntry[] | any
Remove `any` since you have included ITimeEntry as its Type

2023-01-18 02:29 UTC, abduljalilpalala requested changes
Please check comments 💬 , thank you.

2023-01-18 02:29 UTC, abduljalilpalala commented on client/src/components/molecules/MyDailyTimeRecordTable/DesktopTable.tsx
> +            isLoading ? (
```suggestion
          {error === null ? (
            isLoading ? (
```

Check if this code is working, if not refer to the first option
```suggestion
          {error ? (
            isLoading ? (
```

2023-01-18 02:29 UTC, abduljalilpalala commented on client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
Sort out the imports. Made files is at the bottom while package installed are at the top

```
import moment from 'moment'
import { ChevronRight, Clock, Edit } from 'react-feather'

import Chip from '~/components/atoms/Chip'
import { IMyDTR } from '~/utils/interfaces'
import Button from '~/components/atoms/Buttons/Button'
import { WorkStatus } from '~/utils/constants/work-status'
import LineSkeleton from '~/components/atoms/Skeletons/LineSkeleton'
import { IEmployeeTimeEntry } from '~/utils/types/timeEntryTypes'
```

2023-01-18 02:29 UTC, abduljalilpalala commented on client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
> +        isLoading ? (
Refer to the previous comment.

2023-01-18 02:29 UTC, abduljalilpalala commented on client/src/components/molecules/MyDailyTimeRecordTable/index.tsx
> +    error: unknown
Remove `any`

2023-01-18 05:11 UTC, abduljalilpalala approved these changes
### Approved! ✔️

2023-01-18 05:12 UTC, merged