HRIS-361 [Task] Setup Nest.js under api_v2 folder
framgia/sph-hris pull request #297
Opened 2024-06-10 05:26 UTC by mdv-sunasterisk

## Issue Link

Backlog Link

## Definition of Done

- [x]  Setup Nest.js
- [x] Connect to graph QL
- [x] Setup Jest
- [x] Setup Husky pre-commit

## Notes

- Initial commit for the NestJS setup. Includes the necessary configuration to commence the slack API integration.

## Pre-condition

- Run the usual docker commands to update the project. The docker-compose.yml, dockerfile, .dockerignore files have been created/updated accordingly for a seamless update.

## Expected Output

- The NestJS project should be running on port 3001.

## Screenshots/Recordings

Note: Minimal pre-commit alterations were added after the time of recording.

https://github.com/framgia/sph-hris/assets/169010392/c02c0c41-a04f-4e9b-915a-caa284dc5a0b

2024-06-10 07:31 UTC, chevyB commented on api_v2/package.json
> +    "start:debug": "nest start --debug --watch",
its good to have short command when running dev environment
```suggestion
    "dev": "nest start --watch",
    "dev:debug": "nest start --debug --watch",
```

2024-06-10 07:31 UTC, chevyB commented on api_v2/tsconfig.json
> +    "noImplicitAny": false,
much better if we follow strict implementation 
```suggestion
    "strictNullChecks": true,
    "noImplicitAny": true,
```

2024-06-10 07:31 UTC, chevyB commented on api_v2/tsconfig.json
> +{
1. can we add ?
```
    "noUnusedLocals": true,
    "noUnusedParameters": true,
```

2. much better to also have alias
`"paths": { "@/*": ["src/*"] }`

2024-06-10 07:31 UTC, chevyB commented on api_v2/tsconfig.json
> +}
```suggestion
  }
  "exclude": ["node_modules", "dist"]
}
```

2024-06-11 02:08 UTC, chevyB requested changes

2024-06-11 02:08 UTC, chevyB commented on api_v2/package.json
> +    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
i want to include `npm run lint` without fix in husky pre-commit.
So dev can know that there are lint errors to fix and can be familiarize about linting.
```suggestion
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\"",
    "lint:fix": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
```

2024-06-11 02:08 UTC, chevyB commented on docker-compose.yml
> +  # ASP.NET Service
```suggestion
  # NestJS Service
```

2024-06-11 02:08 UTC, chevyB commented on docker-compose.yml
> +  api_v2:
Im just wondering what's the consideration why we containerized the api.
Its good that we have 1 command to run all servers but im worry if our laptops can handle may docker containers.
Is there is no difference about laptop performance running between `npm run dev` or using `docker`?

2024-06-11 02:18 UTC, mdv-sunasterisk commented on docker-compose.yml
> +  api_v2:
I do agree that it feels heavy whenever i try running the docker compose command. Thought there was a deployment benefit to this as to why the previous team implemented this.

Personally, I run the docker compose command to run all of servers apart from api_v2, which i run locally using npm run dev.

May i ask for your thoughts? @chevyB

2024-06-11 02:22 UTC, chevyB commented on docker-compose.yml
> +  api_v2:
I see, its ok to retain the docker but when running local, its beneficial to use `npm run dev`.

2024-06-11 02:26 UTC, mdv-sunasterisk commented on docker-compose.yml
> +  api_v2:
Got it, will apply changes.

2024-06-11 02:39 UTC, chevyB approved these changes

2024-06-11 02:56 UTC, jeremiahC commented on docker-compose.yml
> +  api_v2:
@mdv-sunasterisk @chevyB 
Just additional note though, the purpose of containers or even for VM, is to create a separate environment that will not tamper the host machine.  But I do agree that somehow docker does not have a good review in terms of performance in local environment.

I can agree to just run node in the host machine instead of docker. Docker will be more responsible on infra stuffs like DB.

2024-06-11 02:56 UTC, jeremiahC commented on docker-compose.yml
> +  api_v2:
You can remove this container nalang

2024-06-11 02:57 UTC, jeremiahC commented on docker-compose.yml
> +  api_v2:
ah wait, please keep this lang. I will be considering to deploy backend with docker. Sorry.

2024-06-11 03:07 UTC, mdv-sunasterisk commented on docker-compose.yml
> +  api_v2:
Ok copy, we'll be retaining the api_v2 container. Kindly requesting for next actions @jeremiahC, may I confirm if we're already good for merging?

2024-06-11 05:00 UTC, merged