HRIS-378 Navbar: API migration Fetch User Name and Role
framgia/sph-hris pull request #311
Opened 2024-07-08 11:03 UTC by Miguel21Monacillo

## Issue Link
https://framgiaph.backlog.com/view/HRIS-378

## Definition of Done

- [x] Users can query all Users
- [x] Users can query Users ID for name, role

## Notes
- No specific note entry

## Pre-condition

Commands to run:
- [x] npm run dev

## Expected Output

- [x]`http://localhost:5257/graphql/` and `http://localhost:3001/graphql` should have the same output with the same query
- [x] Can query all users and individual user on NextJS
## Screenshots/Recordings

NestJS query for User ID
![Screenshot 2024-07-08 181849](https://github.com/framgia/sph-hris/assets/142192964/9c92a62d-0838-4577-bd75-1e051a49e3ab)

NestJS query for All Users
![Screenshot 2024-07-08 171147](https://github.com/framgia/sph-hris/assets/142192964/7b4b3e18-c0ae-4b9a-b0cf-bf73c8fdc5dc)

2024-07-09 07:37 UTC, LennardUy104 commented on api_v2/src/user/user.resolver.ts
> +
As discussed yesterday, please add documentation 
Thank you

2024-07-09 07:37 UTC, LennardUy104 commented on api_v2/src/user/user.service.ts
> +
As discussed yesterday, please add documentation 
Thank you

2024-07-09 07:39 UTC, LennardUy104 requested changes

2024-07-09 07:39 UTC, LennardUy104 commented on api_v2/src/user/user.service.ts
> +  async getUsers(): Promise<User[]> {
As discussed yesterday, please rename it to findAll and findById
Thank you

2024-07-09 07:39 UTC, LennardUy104 commented on api_v2/src/user/user.service.ts
> +  async getUsers(): Promise<User[]> {
As discussed yesterday, please add documentation 
Thank you

2024-07-09 07:39 UTC, LennardUy104 commented on api_v2/src/user/user.resolver.ts
> +@Resolver(() => UserDTO)
As discussed yesterday, please add documentation 
Thank you

2024-07-18 09:14 UTC, Miguel21Monacillo commented on api_v2/src/user/user.service.ts
> +  async getUsers(): Promise<User[]> {
It would be too broad when it comes to the query sir. If I change it to findAll then the query for getUsers would be findAll also and it would be too broad and not specific. I tried changing it but I would have to also change the schema

2024-07-19 09:36 UTC, Fontilllas approved these changes

2024-07-19 09:47 UTC, Fontilllas submitted a review, later dismissed

2024-07-26 03:20 UTC, LennardUy104 approved these changes
Tested and working

2024-07-26 03:20 UTC, merged

2024-10-09 05:02 UTC, Fontilllas commented
Please correct the User Service for this and all required query must be get to implement the integration.