HRIS-61 [Bugtask] Url is wrong when logout
framgia/sph-hris pull request #44
Opened 2023-01-26 09:42 UTC by NiloJr-sun

## Issue Link

https://framgiaph.backlog.com/view/HRIS-61

## Definition of Done

- [x] Fix User logout callback URL

## Notes
- Bug fix only

## Pre-condition
- Run ``` docker compose up --build ```

## Expected Output
- The callback URL for logout should be ``` /sign-in ```

## Screenshots/Recordings

https://user-images.githubusercontent.com/109492180/214801988-ceb319c5-3769-4d15-a3de-50588e98de94.mp4

2023-01-26 10:15 UTC, jsvelte approved these changes
# Approved 💯

2023-01-26 10:15 UTC, rogeliojohnoliverio approved these changes
Approved 🙇

2023-01-27 04:15 UTC, arden-dave approved these changes

2023-01-27 04:16 UTC, arden-dave commented
Approved. 👍

2023-01-27 05:08 UTC, abduljalilpalala commented on client/src/pages/sign-in.tsx
>        toast.success('Verification Success, redirecting...', { duration: 3000 })
Let's `window.location.href = '/'` when logging out the user instead of `router.push `

2023-01-27 05:08 UTC, abduljalilpalala requested changes
Please check comments. 💬

2023-01-27 06:57 UTC, abduljalilpalala approved these changes
### Approved! ✅

2023-01-27 06:57 UTC, merged