HRIS-100 [BugTask] Error implement the Download function
framgia/sph-hris pull request #79
Opened 2023-02-08 09:54 UTC by NiloJr-sun

## Issue Link

https://framgiaph.backlog.com/view/HRIS-100

## Definition of Done

- [x] Users can download the file uploaded using the download button directly

## Notes
- Bug fix only
- Added minor changes on the ``` _document.tsx ``` based on sir Joshua's instruction.

## Pre-condition
- In the client directory, access your ``` .env.local ``` file and replace the existing ``` NEXT_PUBLIC_MEDIA_URL ``` value to ``` http://localhost:3000/media/ ```
- In the root directory, run ``` docker compose up --build ```

## Expected Output
- It should force download the file upon clicking on the download button

## Screenshots/Recordings

https://user-images.githubusercontent.com/109492180/217495902-63c5a8f4-0722-4624-9d54-d22119d3e654.mp4

2023-02-09 06:09 UTC, jsvelte approved these changes
# Approved 💯

2023-02-10 07:00 UTC, abduljalilpalala commented on client/src/components/organisms/ViewDetailsDrawer/index.tsx
>        .then((blobobject) => {
Put this in a try catch block, and display a toast once an error has occurred

2023-02-10 07:00 UTC, abduljalilpalala requested changes
Please check comments 💬

2023-02-13 06:22 UTC, abduljalilpalala commented on client/next.config.js
> +        }media/timeinservice/:path*`
Instead of hard coding the localhost, you can use the variable from the .env file.

2023-02-13 06:22 UTC, abduljalilpalala commented on client/src/components/organisms/ViewDetailsDrawer/index.tsx
>            </div>
Remove comment if not used.

2023-02-13 06:23 UTC, abduljalilpalala requested changes
Please check comments. 💬

2023-02-13 10:29 UTC, abduljalilpalala approved these changes
### Approved! ✅

2023-02-13 10:29 UTC, merged