HRIS-122 [FE] Integrate Send notification when filing a leave request functionality
framgia/sph-hris pull request #97
Opened 2023-02-21 09:19 UTC by arden-dave

## Issue Link
https://framgiaph.backlog.com/view/HRIS-122

## Definition of Done
- [x] Reintegrated filling of leave feature
- [x] Notification indicator when receiving real time notification in FE
- [x] Added validation on BE implementation of creating leave
- [x] Fixed issue where manager receives 2 notification for one leave request

## Notes
- You need to re-login to check this feature
- To test the real-time notification on the FE, you can set your own role to `Manager` or `ProjectLeader` in the database. Then file leave using the form selecting yourself as manager or project leader.
- Or you can create leave request in the graphql playground using this mutation
```
mutation($leave: CreateLeaveRequestInput!){
  createLeave(leave: $leave){
    id
  }
}
```
- with variables (change `managerId` or `projectLeaderId` to your own user id)
```
{
  "leave": {
    "userId": 4,
    "leaveTypeId": 3,
    "managerId": 70,
    "otherProject": "",
    "reason": "qweqwe",
    "leaveDates": [
      {
        "leaveDate": "2023-02-17",
        "isWithPay": true,
        "days": 0.625
      }
    ],
    "leaveProjects": [
      {
        "projectId": 1,
        "projectLeaderId": 4
      },
      {
        "projectId": 2,
        "projectLeaderId": 2
      }
    ]
  }
}
```

## Pre-condition
- add `NEXT_PUBLIC_BACKEND_WEBSOCKET_URL=ws://localhost:5257/graphql` to the `.env.local` on the `client` directory
- run `npm install` on the `client` directory
- run `docker compose up --build`

## Expected Output
- User should now be able to file leave again
- When receiving notification, there should be a number on top of the bell icon indicating new notifications
- The notification number should persist even when changing pages or reloading

## Screenshots/Recordings
- Notification number indicator
![image](https://user-images.githubusercontent.com/111718037/220300043-90a37bec-7c5f-4a03-bdcc-3bfd03a549b2.png)

- When there are more than 9 unread notifications
![image](https://user-images.githubusercontent.com/111718037/220299853-a57fe373-3f8e-46d0-a6a3-2218fd43e9dc.png)

- Recording

[NotificationIndicator.webm](https://user-images.githubusercontent.com/111718037/220302076-a82f3efc-3b58-448c-bf1c-49403498da96.webm)

2023-02-21 09:37 UTC, jsvelte approved these changes
# Approved 💯

2023-02-22 02:06 UTC, abduljalilpalala commented on api/Utils/Validation.cs
> +            return true;
Try and check if this will work.

```suggestion
            return (leaveDates == null || leaveDates.Count == 0);
```

2023-02-22 02:07 UTC, abduljalilpalala commented on api/Utils/Validation.cs
> +            return true;
```suggestion
            return (leaveProjects == null || leaveProjects.Count == 0);
```

2023-02-22 02:09 UTC, abduljalilpalala requested changes
Please check comments 💬

2023-02-22 03:19 UTC, merged